### ISSUE TITLE
Stop at major version?

### ISSUE THREAD

**Issue by ulysses4ever** [nomeata/cabal-plan-bounds#22]
Quoting the readme:

```diff
diff --git a/cabal-plan-bounds.cabal b/cabal-plan-bounds.cabal
index 1db21ca..a99e7bc 100644
--- a/cabal-plan-bounds.cabal
+++ b/cabal-plan-bounds.cabal
@@ -20,9 +20,12 @@ executable cabal-plan-bounds
     import:           warnings
     main-is:          Main.hs
     other-modules:    ReplaceDependencies
-    build-depends:    base, Cabal-syntax, cabal-plan,
-                      optparse-applicative, containers,
-                      text
-    build-depends:    bytestring,
+    build-depends:    base ^>=4.14.3 || ^>=4.15.1 || ^>=4.16.4 || ^>=4.17.0,
+                      Cabal-syntax ^>=3.8.1,
+                      cabal-plan ^>=0.7.2,
+                      optparse-applicative ^>=0.17.0,
+                      containers ^>=0.6.4,
+                      text ^>=1.2.4 || ^>=2.0.1
+    build-depends:    bytestring ^>=0.10.12 || ^>=0.11.3
     hs-source-dirs:   src/
     default-language: Haskell2010
```

To my eye, minor versions like `0.11.3` look strange as PVP dictates that 0.11.* covers "non-breaking changes". So, I'd prefer having `^>= 0.11` instead. Would that be possible? Maybe as a flag. But I think in general people would get on board quicker if they saw less noisy major-only bounds.

In all honesty, PVP says "new bindings" are not breaking, which is not really true. But I'd take a gamble. 

If I ran the tool on regular basis, I'd probably be interested in choosing which packages I want to be pinned to minor versions and which to major ones. So, yeah: flags or even a config for such fine tuning would be most helpful.

**Comment by nomeata** [comment]
Hmm, is that sound? If your project uses one of the new bindings in `0.11.3`, then `0.11.*` seems a lie, doesn't it?

I’m wary of making this configurable; one value proposition of this tool that it helps to stop thinking about version bounds to some extent.

If you want more control, then my suggestion is to use one (or more) `cabal.project` files to make sure you test your package against `0.11.0` (or whatever the fist version is), and this way you’ll get `^>= 0.11.0` in your cabal file, covering the widest possible version range.

**Comment by ulysses4ever** [comment]
Noted, thank you.
