### ISSUE TITLE
Hackage build fails

### ISSUE THREAD

**Issue by andreasabel** [nomeata/cabal-plan-bounds#3]
Hackage seems to currently use GHC 9.2.4 which cannot build `cabal-plan-bounds-0.1` because it insists on `base-4.16.4`, but 9.2.4 comes with `base-4.16.3`: https://hackage.haskell.org/package/cabal-plan-bounds-0.1/reports/2

Maybe pinning down `base` to the minor version is a bit too paranoid?
(I see that you applied `cabal-plan-bounds` to itself, but maybe for `base` one needs manual adjustments?)

**Comment by nomeata** [comment]
Ah, interesting case. I use these configs at the moment, and derive the bounds from them
```
$ ls ci-configs/
ghc-8.10.7.config  ghc-9.0.2.config  ghc-9.2.5.config  ghc-9.4.4.config  stackage-nightly.config
```

> Maybe pinning down base to the minor version is a bit too paranoid?

Not sure: Unless I actually build against base 4.16.3, I don’t know for sure that I am not using anything that was introduced in 4.164.

So let me add 9.2.4 to CI…
